stages:
  - build
  - deploy

build_navigator:
  image: node:21
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - layers/*
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never
  script:
    - bash scripts/build-navigator.sh
  artifacts:
    paths:
    - public

pages:
  stage: deploy
  script:
  - echo "nothing to do"
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      changes:
        - layers/*
    - if: $CI_PIPELINE_SOURCE == "web"
    - when: never
